import 'dart:convert';
import 'dart:io';

/// The Android launcher's static shortcut labels (#286) and what the App
/// Functions say (#289), as translation key => resource name. Dynamic
/// shortcuts carry the user's own template names and need nothing here.
const androidShortcutKeys = {
  'androidShortcutStart': 'shortcut_start_workout',
  // what the App Functions say (#289), read by HeartFunctions.kt
  'androidFunctionNoWorkout': 'function_no_workout',
  'androidFunctionNoRest': 'function_no_rest',
  'androidFunctionNoTimer': 'function_no_timer',
  'androidFunctionResting': 'function_resting',
  'androidFunctionRestExtended': 'function_rest_extended',
  'androidFunctionRestSkipped': 'function_rest_skipped',
  'androidFunctionLogged': 'function_logged',
  'androidFunctionNothingLeft': 'function_nothing_left',
  'androidFunctionSayValues': 'function_say_values',
  'androidFunctionCouldNotAnswer': 'function_could_not_answer',
  'androidFunctionUnknownExercise': 'function_unknown_exercise',
  'androidFunctionUnknownTemplate': 'function_unknown_template',
  'androidFunctionOpening': 'function_opening',
  'androidFunctionAppClosed': 'function_app_closed',
};

/// Keeps the launcher's labels on the same translation import as Flutter:
/// `values/strings_shortcuts.xml` for English and `values-<lang>/` for every
/// other base language. Regional locales inherit the base language, as they
/// do on iOS.
void writeAndroidLocalizations(Map<String, Map<String, dynamic>> translations, Directory res) {
  final languages = translations.keys.where((locale) => !locale.contains('_')).toList()..sort();
  final contents = <String, String>{};
  for (final language in languages) {
    contents[language] = androidStrings(translations, language);
  }
  // Validate every translation before replacing any native resource.
  for (final entry in contents.entries) {
    final folder = switch (entry.key) {
      'en' => 'values',
      String language => 'values-$language',
    };
    final directory = Directory('${res.path}/$folder')..createSync(recursive: true);
    File('${directory.path}/strings_shortcuts.xml').writeAsStringSync(entry.value);
  }
}

/// One `strings.xml` body for [language].
String androidStrings(Map<String, Map<String, dynamic>> translations, String language) {
  final strings = androidShortcutKeys.entries.map((entry) {
    final value = translations[language]?[entry.key];
    if (value is! String || value.trim().isEmpty) {
      throw StateError('Missing Android shortcut translation: $language/${entry.key}');
    }
    return '    <string name="${entry.value}">${_escaped(value)}</string>';
  });
  return '<?xml version="1.0" encoding="utf-8"?>\n'
      '<!-- Generated by heart_language translation import. Do not edit. -->\n'
      '<resources>\n${strings.join('\n')}\n</resources>\n';
}

/// What the resource compiler reads as text: XML's own characters as
/// entities, and the quotes it treats as markup — an apostrophe ends a
/// string, a double quote starts a quoted run — behind a backslash. An entity
/// does not do: aapt2 resolves `&#39;` to the apostrophe first and then
/// chokes on it.
String _escaped(String value) {
  return const HtmlEscape(.element).convert(value).replaceAll("'", r"\'").replaceAll('"', r'\"');
}
