import 'dart:convert';
import 'dart:io';

/// The Android launcher's static shortcut labels (#286), as translation key =>
/// resource name. Dynamic shortcuts carry the user's own template names and
/// need nothing here.
const androidShortcutKeys = {
  'androidShortcutStart': 'shortcut_start_workout',
};

/// Keeps the launcher's labels on the same translation import as Flutter:
/// `values/strings_shortcuts.xml` for English and `values-<lang>/` for every
/// other base language. Regional locales inherit the base language, as they
/// do on iOS.
void writeAndroidLocalizations(Map<String, Map<String, dynamic>> translations, Directory res) {
  final languages = translations.keys.where((locale) => !locale.contains('_')).toList()..sort();
  final contents = <String, String>{};
  for (final language in languages) {
    contents[language] = androidStrings(translations, language);
  }
  // Validate every translation before replacing any native resource.
  for (final entry in contents.entries) {
    final folder = switch (entry.key) {
      'en' => 'values',
      String language => 'values-$language',
    };
    final directory = Directory('${res.path}/$folder')..createSync(recursive: true);
    File('${directory.path}/strings_shortcuts.xml').writeAsStringSync(entry.value);
  }
}

/// One `strings.xml` body for [language].
String androidStrings(Map<String, Map<String, dynamic>> translations, String language) {
  final strings = androidShortcutKeys.entries.map((entry) {
    final value = translations[language]?[entry.key];
    if (value is! String || value.trim().isEmpty) {
      throw StateError('Missing Android shortcut translation: $language/${entry.key}');
    }
    return '    <string name="${entry.value}">${_escaped(value)}</string>';
  });
  return '<?xml version="1.0" encoding="utf-8"?>\n'
      '<!-- Generated by heart_language translation import. Do not edit. -->\n'
      '<resources>\n${strings.join('\n')}\n</resources>\n';
}

/// XML escaping that also keeps the resource compiler's own markup out: an
/// apostrophe or a quote becomes its entity, which it reads as text.
String _escaped(String value) => const HtmlEscape(.unknown).convert(value);
