import 'dart:convert';
import 'dart:io';

const _healthKeys = {
  'iosHealthShareUsageDescription': 'NSHealthShareUsageDescription',
  'iosHealthUpdateUsageDescription': 'NSHealthUpdateUsageDescription',
};

/// Keep the native permission sheet and its English fallback on the same
/// translation import as Flutter. Regional locales inherit the base language.
void writeIosLocalizations(Map<String, Map<String, dynamic>> translations, Directory runner) {
  final languages = translations.keys.where((locale) => !locale.contains('_')).toList()..sort();
  final contents = <String, String>{};
  for (final language in languages) {
    final strings = _healthKeys.entries
        .map((entry) {
          final value = translations[language]![entry.key];
          if (value is! String || value.trim().isEmpty) {
            throw StateError('Missing iOS permission translation: $language/${entry.key}');
          }
          return '"${entry.value}" = ${_quoted(value)};';
        })
        .join('\n');
    contents[language] = '// Generated by heart_language translation import. Do not edit.\n$strings\n';
  }

  final plistFile = File('${runner.path}/Info.plist');
  var plist = plistFile.readAsStringSync();
  for (final entry in _healthKeys.entries) {
    final english = translations['en']?[entry.key];
    if (english is! String || english.trim().isEmpty) {
      throw StateError('Missing English iOS permission translation: ${entry.key}');
    }
    final pattern = RegExp('(<key>${entry.value}</key>\\s*<string>)[^<]*(</string>)');
    if (pattern.allMatches(plist).length != 1) {
      throw StateError('Expected exactly one ${entry.value} in ${plistFile.path}');
    }
    plist = plist.replaceFirstMapped(
      pattern,
      (match) => '${match[1]}${const HtmlEscape(.element).convert(english)}${match[2]}',
    );
  }

  // Validate every translation before replacing any native resource.
  for (final entry in contents.entries) {
    final directory = Directory('${runner.path}/${entry.key}.lproj')..createSync(recursive: true);
    File('${directory.path}/InfoPlist.strings').writeAsStringSync(entry.value);
  }
  plistFile.writeAsStringSync(plist);
}

String _quoted(String value) =>
    '"${value.replaceAll(r'\', r'\\').replaceAll('"', r'\"').replaceAll('\n', r'\n').replaceAll('\r', r'\r').replaceAll('\t', r'\t')}"';
