import 'dart:convert';
import 'dart:io';

/// The phone app's permission sheets, as translation key => Info.plist key.
const runnerHealthKeys = {
  'iosHealthShareUsageDescription': 'NSHealthShareUsageDescription',
  'iosHealthUpdateUsageDescription': 'NSHealthUpdateUsageDescription',
};

/// The watch app's (#184): the same two plist keys, its own words — it reads
/// and writes different things.
const watchHealthKeys = {
  'iosWatchHealthShareUsageDescription': 'NSHealthShareUsageDescription',
  'iosWatchHealthUpdateUsageDescription': 'NSHealthUpdateUsageDescription',
};

/// Keep the native permission sheet and its English fallback on the same
/// translation import as Flutter. Regional locales inherit the base language.
///
/// [runner] is the target's folder — the one holding its Info.plist and its
/// `.lproj` folders — and [healthKeys] the strings that target shows.
void writeIosLocalizations(
  Map<String, Map<String, dynamic>> translations,
  Directory runner, {
  Map<String, String> healthKeys = runnerHealthKeys,
}) {
  final languages = translations.keys.where((locale) => !locale.contains('_')).toList()..sort();
  final contents = <String, String>{};
  for (final language in languages) {
    final strings = healthKeys.entries
        .map((entry) {
          final value = translations[language]![entry.key];
          if (value is! String || value.trim().isEmpty) {
            throw StateError('Missing iOS permission translation: $language/${entry.key}');
          }
          return '"${entry.value}" = ${_quoted(value)};';
        })
        .join('\n');
    contents[language] = '// Generated by heart_language translation import. Do not edit.\n$strings\n';
  }

  final plistFile = File('${runner.path}/Info.plist');
  var plist = plistFile.readAsStringSync();
  for (final entry in healthKeys.entries) {
    final english = translations['en']?[entry.key];
    if (english is! String || english.trim().isEmpty) {
      throw StateError('Missing English iOS permission translation: ${entry.key}');
    }
    final pattern = RegExp('(<key>${entry.value}</key>\\s*<string>)[^<]*(</string>)');
    if (pattern.allMatches(plist).length != 1) {
      throw StateError('Expected exactly one ${entry.value} in ${plistFile.path}');
    }
    plist = plist.replaceFirstMapped(
      pattern,
      (match) => '${match[1]}${const HtmlEscape(.element).convert(english)}${match[2]}',
    );
  }

  // Validate every translation before replacing any native resource.
  for (final entry in contents.entries) {
    final directory = Directory('${runner.path}/${entry.key}.lproj')..createSync(recursive: true);
    File('${directory.path}/InfoPlist.strings').writeAsStringSync(entry.value);
  }
  plistFile.writeAsStringSync(plist);
}

String _quoted(String value) =>
    '"${value.replaceAll(r'\', r'\\').replaceAll('"', r'\"').replaceAll('\n', r'\n').replaceAll('\r', r'\r').replaceAll('\t', r'\t')}"';

/// The phone app's App Shortcuts (#285), as translation key => the English
/// string the Swift source uses — which is the catalog's key. Siri phrases go
/// in the `AppShortcuts` table, by Apple's rule; the titles of the intents and
/// their parameter in the default `Localizable` table.
const runnerShortcutPhraseKeys = [
  'iosShortcutPhraseStart',
  'iosShortcutPhraseStartTemplate',
  'iosShortcutPhraseFinish',
  'iosShortcutPhraseStartRest',
  'iosShortcutPhraseRestFor',
  'iosShortcutPhraseAddRest',
  'iosShortcutPhraseSkipRest',
  'iosShortcutPhraseLogSet',
  'iosShortcutPhraseRecord',
  'iosShortcutPhraseLastExercise',
  'iosShortcutPhraseLastTemplate',
  'iosShortcutPhraseWeekly',
];

const runnerShortcutTitleKeys = [
  'iosShortcutStartTitle',
  'iosShortcutFinishTitle',
  'iosShortcutStartIntent',
  'iosShortcutFinishIntent',
  'iosShortcutTemplate',
  'iosShortcutStartRestTitle',
  'iosShortcutExtendRestTitle',
  'iosShortcutSkipRestTitle',
  'iosShortcutStartRestIntent',
  'iosShortcutExtendRestIntent',
  'iosShortcutSkipRestIntent',
  'iosShortcutRestLength',
  'iosShortcutLengthParam',
  'iosShortcutThirtySeconds',
  'iosShortcutOneMinute',
  'iosShortcutNinetySeconds',
  'iosShortcutTwoMinutes',
  'iosShortcutThreeMinutes',
  'iosShortcutResting',
  'iosShortcutRestExtended',
  'iosShortcutRestSkipped',
  'iosShortcutNoWorkout',
  'iosShortcutNoRest',
  'iosShortcutNoTimer',
  'iosShortcutLogSetTitle',
  'iosShortcutLogSetIntent',
  'iosShortcutWeightParam',
  'iosShortcutRepsParam',
  'iosShortcutLogged',
  'iosShortcutNothingLeft',
  'iosShortcutSayValues',
  'iosShortcutAskWeight',
  'iosShortcutAskReps',
  'iosShortcutRecordTitle',
  'iosShortcutLastTimeTitle',
  'iosShortcutLastSessionTitle',
  'iosShortcutWeeklyTitle',
  'iosShortcutRecordIntent',
  'iosShortcutLastExerciseIntent',
  'iosShortcutLastTemplateIntent',
  'iosShortcutWeeklyIntent',
  'iosShortcutExercise',
  'iosShortcutCouldNotAnswer',
];

/// Writes the Siri phrases and the titles beside the Runner's Info.plist. The
/// English value is the key, since that is what the Swift source says; the
/// other base languages are its localizations, and regional locales inherit
/// the base language.
///
/// Two formats, because the App Shortcuts metadata processor accepts the
/// phrases only as `<lang>.lproj/AppShortcuts.strings` on a deployment target
/// below iOS 17; the titles are an ordinary `Localizable.xcstrings`.
void writeIosStringCatalogs(Map<String, Map<String, dynamic>> translations, Directory runner) {
  File('${runner.path}/Localizable.xcstrings').writeAsStringSync(stringCatalog(translations, runnerShortcutTitleKeys));
  final languages = translations.keys.where((locale) => !locale.contains('_')).toList()..sort();
  for (final language in languages) {
    final directory = Directory('${runner.path}/$language.lproj')..createSync(recursive: true);
    File('${directory.path}/AppShortcuts.strings').writeAsStringSync(
      stringsTable(translations, runnerShortcutPhraseKeys, language),
    );
  }
}

/// A `.strings` table for [keys] in [language], keyed by the English value.
String stringsTable(Map<String, Map<String, dynamic>> translations, List<String> keys, String language) {
  final lines = keys.map((key) {
    final english = translations['en']?[key];
    if (english is! String || english.trim().isEmpty) {
      throw StateError('Missing English iOS shortcut translation: $key');
    }
    final value = translations[language]?[key];
    if (value is! String || value.trim().isEmpty) {
      throw StateError('Missing iOS shortcut translation: $language/$key');
    }
    return '${_quoted(english)} = ${_quoted(value)};';
  });
  return '// Generated by heart_language translation import. Do not edit.\n${lines.join('\n')}\n';
}

/// A `.xcstrings` catalog for [keys]: Xcode's JSON, sorted, two-space indented.
String stringCatalog(Map<String, Map<String, dynamic>> translations, List<String> keys) {
  final languages = translations.keys.where((locale) => !locale.contains('_') && locale != 'en').toList()..sort();
  final strings = <String, Object>{};
  for (final key in keys) {
    final english = translations['en']?[key];
    if (english is! String || english.trim().isEmpty) {
      throw StateError('Missing English iOS shortcut translation: $key');
    }
    final localizations = <String, Object>{};
    for (final language in languages) {
      final value = translations[language]![key];
      if (value is! String || value.trim().isEmpty) {
        throw StateError('Missing iOS shortcut translation: $language/$key');
      }
      localizations[language] = {
        'stringUnit': {'state': 'translated', 'value': value},
      };
    }
    strings[english] = {'localizations': localizations};
  }
  final catalog = {
    'sourceLanguage': 'en',
    'strings': {for (final key in strings.keys.toList()..sort()) key: strings[key]},
    'version': '1.0',
  };
  return '${const JsonEncoder.withIndent('  ').convert(catalog)}\n';
}
