default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  # single lane and pass the environment (dev/prod) as an argument
  lane :beta do |options|
    env = options[:env] # 'dev' or 'prod'

    app_id = env == 'prod' ? "me.heart-of.ios" : "me.heart-of.ios.dev"
    scheme = env == 'prod' ? "prod" : "dev"
    configuration = env == 'prod' ? "Release-prod" : "Release-dev"

    setup_ci

    require 'json'
    key_info = JSON.parse(File.read(File.join(__dir__, "appstore_key.json")))

    api_key = app_store_connect_api_key(
      key_id: key_info["keyId"],
      issuer_id: key_info["issuerId"],
      key_filepath: "fastlane/AuthKey_#{key_info["keyId"]}.p8",
      duration: 1200,
      in_house: false
    )

    match(
      type: "appstore",
      app_identifier: app_id,
      readonly: true
    )

    # Update the Xcode project directly for the Runner target only
    # This bypasses the global SPM signing bug
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: "DFX2JYT8BM",
      code_sign_identity: "Apple Distribution",
      profile_name: "match AppStore #{app_id}",
      targets: ["Runner"],
      build_configurations: [configuration]
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: scheme,
      configuration: configuration,
      export_method: "app-store"
    )

#     build_app(
#       workspace: "Runner.xcworkspace",
#       scheme: scheme,
#       configuration: configuration,
#       export_method: "app-store",
#       xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' DEVELOPMENT_TEAM='DFX2JYT8BM' PROVISIONING_PROFILE_SPECIFIER='match AppStore #{app_id}'"
#     )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end