name: heart_charts
description: "Chart widgets"
version: 0.0.1
publish_to: none

environment:
  sdk: "^3.13.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.2.0

resolution: workspace

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
