part of 'router.dart';

const _profileName = 'profile';
const _profilePath = '/$_profileName';
const _loginName = 'login';
const _loginPath = '/$_loginName';
const _settingsName = 'settings';
const _settingsPath = _settingsName;
const _avatarPath = '/avatar';
const _avatarName = 'avatar';
const _workoutName = 'workout';
const _workoutPath = '/$_workoutName';
const _templateEditorName = 'templateEditor';
const _recoveryName = 'recovery';
const _signUpName = 'signUp';
const _historyName = 'history';
const _historyPath = '/$_historyName'; // a callback in bottom navigation bar in app_frame.dart relies on this
const _historyEditName = 'edit';
const _exercisesName = 'exercises';
const _exercisesPath = '/$_exercisesName';
const _exerciseDetailName = 'exerciseDetail';
const _exerciseArchivedDetailName = 'exerciseArchivedDetail';
const _exerciseArchive = 'archive';
const _doneName = 'done';
const _donePath = '/$_doneName';
const _accountManagementPath = 'account';
const _accountManagementName = _accountManagementPath;
const _restoreAccountName = 'restoreAccount';
const _restoreAccountPath = '/$_restoreAccountName';
const _applePath = '/apple';
const _activeWorkoutPath = '/activeWorkout'; // a notifications redirect in app.dart relies on this
const _upgradeAppName = 'upgradeApp';
const _upgradeAppPath = '/$_upgradeAppName';
const _galleryName = 'gallery';
const _galleryPath = '/$_galleryName';
