name: "iOS Prod Deployment"

on:
  push:
    tags:
      - "v*"
      - "ios*"
  workflow_dispatch: { }

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    uses: ./.github/workflows/testflight-ios-deployment.yml
    with:
      aws_region: "ca-central-1"
      aws_role: "arn:aws:iam::922419543441:role/heart-github-actions-deploy-role"
      secrets_bucket: "922419543441-ca-central-1-static"
      environment: "prod"
      flavor: "prod"